package com.raerossi.pokedex.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFAF2D31)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD7)
val md_theme_light_onPrimaryContainer = Color(0xFF410005)
val md_theme_light_secondary = Color(0xFF984061)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF3E001D)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF97F0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF7C757E)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A1A)
val md_theme_light_surface = Color(0xFFFFF8F7)
val md_theme_light_onSurface = Color(0xFF201A1A)
val md_theme_light_surfaceVariant = Color(0xFFE9DFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4B454D)
val md_theme_light_inverseSurface = Color(0xFF362F2F)
val md_theme_light_inverseOnSurface = Color(0xFFFBEEEE)
val md_theme_light_inversePrimary = Color(0xFFFFB3AF)
val md_theme_light_surfaceTint = Color(0xFFAF2D31)
val md_theme_light_outlineVariant = Color(0xFFCDC4CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB3AF)
val md_theme_dark_onPrimary = Color(0xFF68000D)
val md_theme_dark_primaryContainer = Color(0xFF8E121C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD7)
val md_theme_dark_secondary = Color(0xFFFFB1C8)
val md_theme_dark_onSecondary = Color(0xFF5E1133)
val md_theme_dark_secondaryContainer = Color(0xFF7B2949)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_tertiary = Color(0xFF4FD8EB)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(0xFF97F0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_background = Color(0xFF201A1A)
val md_theme_dark_onBackground = Color(0xFFECE0E0)
val md_theme_dark_surface = Color(0xFF181212)
val md_theme_dark_onSurface = Color(0xFFD0C4C4)
val md_theme_dark_surfaceVariant = Color(0xFF4B454D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC4CE)
val md_theme_dark_inverseSurface = Color(0xFFECE0E0)
val md_theme_dark_inverseOnSurface = Color(0xFF201A1A)
val md_theme_dark_inversePrimary = Color(0xFFAF2D31)
val md_theme_dark_surfaceTint = Color(0xFFFFB3AF)
val md_theme_dark_outlineVariant = Color(0xFF4B454D)
val md_theme_dark_scrim = Color(0xFF000000)

val md_primary_keyColors = Color(0xFFDC4E4E)
val md_surface_containerHighest = Color(0xFF3A3333)
val md_ref_neutral95 = Color(0xFFFBEEEE)

val md_bottomsheet_gradient = Brush.verticalGradient(
    colors = listOf(
        Color(0xFF120D0D),
        Color(0xFF2B292B),
        Color(0xFF120D0D)
    )
)

val seed = Color(0xFFDC4E4E)